# macOS 10.13 High Sierra pip base packages build and test
os: osx
language: python
python: 2.7
compiler: gcc
virtualenv:
  system_site_packages: true
before_install:
  - brew update
install:
  - pip install numpy matplotlib pyproj Pydap shapely Pillow pytest
  - brew install gmsh
before_script:
  - export LD_LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LIBRARY_PATH"
script:
  - make
  - make unittest
  # Pre-download, to best work with Travis timeout
  #- curl http://store.pangaea.de/Publications/TimmermannR_et_al_2010/RTopo105b_50S.nc -o test/Amundsen_Sea/data/RTopo.nc
  #- make test
